/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    './src/**/*.css',
    './index.html',
  ],
  theme: {
    extend: {
      fontFamily: { sans: ['var(--font-main)'] },
      fontSize: {
        xs: ['var(--text-xs)', { lineHeight: '1rem' }],
        sm: ['var(--text-sm)', { lineHeight: '1.25rem' }],
        base: ['var(--text-md)', { lineHeight: '1.5rem' }],
        lg: ['var(--text-lg)', { lineHeight: '1.75rem' }],
        xl: ['1.125rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        7: 'var(--space-7)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
      },
      colors: {
        background: 'var(--bg)',
        page: 'var(--color-page)',
        surface: 'var(--surface)',
        surfaceAlt: 'var(--surface-2)',
        surfaceMuted: 'var(--color-card-muted)',
        field: 'var(--color-field)',
        border: 'var(--border)',
        borderSoft: 'var(--color-border-soft)',
        textPrimary: 'var(--text)',
        textSecondary: 'var(--text-muted)',
        textMuted: 'var(--text-faint)',
        primary: 'var(--color-primary)',
        primaryHover: 'var(--color-primary-hover)',
        primaryActive: 'var(--color-primary-active)',
        primaryText: 'var(--color-primary-text)',
        accentSuccess: 'var(--accent-success)',
        accentWarning: 'var(--accent-warning)',
        accentError: 'var(--accent-error)',
        accentInfo: 'var(--accent-info)',
        brandAccent: 'var(--brand-accent)',
        premium: 'var(--color-premium)',
        overlay: 'var(--color-overlay)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        card: 'var(--radius-card)',
        input: 'var(--radius-control)',
        control: 'var(--radius-control)',
        controlSm: 'var(--radius-control-sm)',
        button: 'var(--radius-control)',
        modal: 'var(--radius-modal)',
        dropdown: 'var(--radius-dropdown)',
        pill: 'var(--radius-pill)',
      },
      boxShadow: {
        layer: 'var(--shadow-layer)',
        card: 'var(--shadow-card)',
        dropdown: 'var(--shadow-dropdown)',
        modal: 'var(--shadow-modal)',
        toast: 'var(--shadow-toast)',
        focus: 'var(--shadow-focus)',
      },
      transitionDuration: {
        DEFAULT: '150',
      },
      scale: {
        98: '0.98',
      },
    },
  },
  plugins: [],
};
