import {getTodayInput} from "../utils/dateHelpers.js";

export const initialMessageTemplates = [
  {
    id: 1,
    name: "Возвращение клиента",
    channel: "SMS",
    language: "Русский",
    audience: "Все",
    subject: "",
    body: "Здравствуйте, {name}! Давно вас не видели в NUAR. Будем рады подобрать удобное время для массажа.",
  },
  {
    id: 2,
    name: "Powrót do salonu",
    channel: "SMS",
    language: "Польский",
    audience: "Поляки",
    subject: "",
    body: "Dzień dobry, {name}! Dawno nie widzieliśmy się w NUAR. Chętnie znajdziemy dogodny termin masażu.",
  },
  {
    id: 3,
    name: "We miss you",
    channel: "Email",
    language: "Английский",
    audience: "Англичане",
    subject: "Your next massage at NUAR",
    body: "Hello, {name}! We have not seen you at NUAR for a while. Reply to this message and we will find a convenient time for your next massage.",
  },
  {
    id: 4,
    name: "Напоминание для девушек",
    channel: "SMS",
    language: "Русский",
    audience: "Девушки",
    subject: "",
    body: "Здравствуйте, {name}! Приглашаем вас снова уделить время себе. В NUAR поможем подобрать удобное окно.",
  },
  {
    id: 5,
    name: "Напоминание для парней",
    channel: "SMS",
    language: "Русский",
    audience: "Парни",
    subject: "",
    body: "Здравствуйте, {name}! Пора восстановиться после нагрузки. Напишите нам, и подберём удобное время для массажа.",
  },
];

export const defaultAppSettings = {
  studioName: "NUAR",
  ownerName: "Влад",
  accentColor: "#8B7CFF",
  colorTheme: "dark",
  theme: "dark",
  sidebarVisible: true,
  compactMode: true,
  animationsEnabled: true,
  notificationsEnabled: true,
  taskAlertsEnabled: true,
  supplyAlertsEnabled: true,
  packageBalanceAlertsEnabled: true,
  certificateAlertsEnabled: true,
  certificateExpiryReminderDays: 30,
  certificateLowBalancePercent: 20,
  smsRemindersEnabled: false,
  smsReminder24hEnabled: true,
  smsReminder2hEnabled: true,
  smsReminder24hTemplate:
    "Dzien dobry, {name}! Przypominamy o wizycie w {studio} jutro {date} o {time}. {service}",
  smsReminder2hTemplate:
    "Dzien dobry, {name}! Za 2 godziny czekamy na Ciebie w {studio} o {time}. {master}",
  smsAutoProcessEnabled: true,
  smsAutoProcessMinutes: 10,
  smsSenderName: "NUAR",
  smsRemindersLastRunAt: "",
  telegramDigestEnabled: false,
  telegramDigestTime: "08:00",
  telegramChatId: "",
  telegramDigestLastRunAt: "",
  siteBookingNotifyTelegramEnabled: true,
  siteBookingNotifyWhatsappEnabled: true,
  ownerNotifyPhone: "",
  reviewRequestsEnabled: false,
  reviewRequestDelayHours: 2,
  reviewRequestTemplate:
    "Dziekujemy za wizyte w {studio}, {name}! Bedziemy wdzieczni za opinie: {reviewUrl}",
  reviewGoogleUrl: "",
  reviewBooksyUrl: "",
  reviewPrimaryUrl: "",
  reviewRequestAutoProcessEnabled: true,
  reviewRequestAutoProcessMinutes: 15,
  reviewRequestLastRunAt: "",
  inactiveFollowUpEnabled: false,
  inactiveFollowUp14Enabled: true,
  inactiveFollowUp30Enabled: true,
  inactiveFollowUp60Enabled: true,
  inactiveFollowUp14Template:
    "Czesc {name}! Tesknilismy za Toba w {studio}. Minely juz {days} dni od ostatniej wizyty. Chetnie pomozemy zarezerwowac termin.",
  inactiveFollowUp30Template:
    "Czesc {name}! W {studio} pamietamy o Tobie. Minelo juz {days} dni bez wizyty - odezwij sie, ustalimy dogodny termin.",
  inactiveFollowUp60Template:
    "Czesc {name}! Czekamy na Ciebie w {studio}. Minelo {days} dni od ostatniej wizyty - wroc do regularnych masazy u nas.",
  inactiveFollowUpAutoProcessEnabled: true,
  inactiveFollowUpAutoProcessMinutes: 60,
  inactiveFollowUpLastRunAt: "",
  waitlistEnabled: true,
  waitlistOfferTemplate:
    "Witaj {name}! Zwolnil sie termin {date} o {time} u {master} ({service}). Czy jestes zainteresowana?",
  forecastAlertsEnabled: true,
  alertAggregationEnabled: true,
  inactiveClientAlertLimit: 5,
  inactiveClientAlertsEnabled: true,
  inactiveClientDays: 14,
  birthdayAlertsEnabled: true,
  birthdayReminderDays: 7,
  todayVisitAlertsEnabled: true,
  todayVisitAlertMode: "remaining",
  upcomingVisitMinutes: 180,
  smartVisitPopupsEnabled: true,
  smartVisitPopupMinutes: 15,
  quietHoursEnabled: true,
  quietHoursStart: "22:00",
  quietHoursEnd: "08:00",
  calendarRemindersVisible: true,
  calendarShowTasks: true,
  calendarNowLineVisible: true,
  calendarConflictWarnings: true,
  workdayStart: "08:00",
  workdayEnd: "22:00",
  calendarSlotMinutes: 15,
  gmailClientId: "",
};

export const DEFAULT_STATS_DATE = getTodayInput();
