import clsx from "clsx";
import {
  Activity,
  AlertTriangle,
  AtSign,
  BadgeCheck,
  Ban,
  BarChart2,
  Banknote,
  Bell,
  BellRing,
  BriefcaseBusiness,
  CakeSlice,
  Calendar,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  CalendarRange,
  Calculator,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Copy,
  Crown,
  CreditCard,
  CloudUpload,
  DatabaseBackup,
  Download,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Gift,
  Gem,
  Globe,
  GripVertical,
  Home,
  Info,
  KeyRound,
  LayoutGrid,
  Lightbulb,
  List,
  LoaderCircle,
  Lock,
  LockKeyhole,
  LogOut,
  LogIn,
  Link2,
  Mail,
  MailCheck,
  MailSearch,
  Medal,
  Menu,
  MessageSquare,
  MessageSquareText,
  Minus,
  MoreHorizontal,
  MoreVertical,
  Package,
  PackagePlus,
  Phone,
  Plus,
  Power,
  QrCode,
  RefreshCw,
  ReceiptText,
  RotateCcw,
  Rocket,
  Save,
  Search,
  Send,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Star,
  StickyNote,
  Sun,
  Trash2,
  Unplug,
  Unlock,
  Upload,
  User,
  UserRound,
  UserPlus,
  Users,
  Wallet,
  WalletCards,
  X,
} from "lucide-react";
import styles from "./AppIcon.module.css";

const appIcons = {
  activity: Activity,
  alert: AlertTriangle,
  at: AtSign,
  badgeCheck: BadgeCheck,
  ban: Ban,
  barChart: BarChart2,
  banknote: Banknote,
  bell: Bell,
  bellRing: BellRing,
  briefcase: BriefcaseBusiness,
  cake: CakeSlice,
  calendar: Calendar,
  calendarClock: CalendarClock,
  calendarDays: CalendarDays,
  calendarPlus: CalendarPlus,
  calendarRange: CalendarRange,
  calculator: Calculator,
  check: Check,
  checkCircle: CheckCircle2,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clipboardCheck: ClipboardCheck,
  clipboardList: ClipboardList,
  clock: Clock,
  copy: Copy,
  crown: Crown,
  creditCard: CreditCard,
  cloudUpload: CloudUpload,
  databaseBackup: DatabaseBackup,
  download: Download,
  edit: Edit3,
  external: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  fileText: FileText,
  filter: Filter,
  gift: Gift,
  gem: Gem,
  globe: Globe,
  grip: GripVertical,
  home: Home,
  info: Info,
  key: KeyRound,
  layoutGrid: LayoutGrid,
  lightbulb: Lightbulb,
  list: List,
  loader: LoaderCircle,
  lock: Lock,
  lockKeyhole: LockKeyhole,
  logout: LogOut,
  login: LogIn,
  link: Link2,
  mail: Mail,
  mailCheck: MailCheck,
  mailSearch: MailSearch,
  medal: Medal,
  menu: Menu,
  message: MessageSquare,
  messageText: MessageSquareText,
  minus: Minus,
  more: MoreHorizontal,
  moreVertical: MoreVertical,
  package: Package,
  packagePlus: PackagePlus,
  phone: Phone,
  plus: Plus,
  power: Power,
  qr: QrCode,
  refresh: RefreshCw,
  receipt: ReceiptText,
  rotateCcw: RotateCcw,
  rocket: Rocket,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  shield: ShieldCheck,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  star: Star,
  stickyNote: StickyNote,
  sun: Sun,
  trash: Trash2,
  unplug: Unplug,
  unlock: Unlock,
  upload: Upload,
  user: User,
  userRound: UserRound,
  userPlus: UserPlus,
  users: Users,
  wallet: Wallet,
  walletCards: WalletCards,
  x: X,
};

export default function AppIcon({
  className,
  decorative,
  icon,
  label,
  name,
  size = "md",
  spin = false,
  strokeWidth = 1.8,
  ...props
}) {
  const Icon = icon || appIcons[name] || Info;
  const isDecorative = decorative ?? !label;

  return (
    <Icon
      aria-hidden={isDecorative ? "true" : undefined}
      aria-label={isDecorative ? undefined : label}
      className={clsx(styles.icon, styles[size] ?? styles.md, spin && styles.spin, className)}
      focusable="false"
      role={isDecorative ? undefined : "img"}
      strokeWidth={strokeWidth}
      {...props}
    />
  );
}
