import clsx from "clsx";
import {
  AlertTriangle,
  AtSign,
  BadgeCheck,
  Ban,
  Bell,
  Calendar,
  CalendarPlus,
  Calculator,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardCheck,
  Clock,
  Copy,
  Crown,
  CreditCard,
  Download,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Gift,
  Globe,
  GripVertical,
  Home,
  Info,
  KeyRound,
  Lightbulb,
  LoaderCircle,
  Lock,
  LockKeyhole,
  LogOut,
  LogIn,
  Link2,
  Mail,
  MailCheck,
  Menu,
  MessageSquare,
  Minus,
  MoreHorizontal,
  MoreVertical,
  Package,
  PackagePlus,
  Phone,
  Plus,
  QrCode,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Sparkles,
  Star,
  StickyNote,
  Trash2,
  Unplug,
  Unlock,
  User,
  Wallet,
  X,
} from "lucide-react";
import styles from "./AppIcon.module.css";

const appIcons = {
  alert: AlertTriangle,
  at: AtSign,
  badgeCheck: BadgeCheck,
  ban: Ban,
  bell: Bell,
  calendar: Calendar,
  calendarPlus: CalendarPlus,
  calculator: Calculator,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clipboardCheck: ClipboardCheck,
  clock: Clock,
  copy: Copy,
  crown: Crown,
  creditCard: CreditCard,
  download: Download,
  edit: Edit3,
  external: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  fileText: FileText,
  filter: Filter,
  gift: Gift,
  globe: Globe,
  grip: GripVertical,
  home: Home,
  info: Info,
  key: KeyRound,
  lightbulb: Lightbulb,
  loader: LoaderCircle,
  lock: Lock,
  lockKeyhole: LockKeyhole,
  logout: LogOut,
  login: LogIn,
  link: Link2,
  mail: Mail,
  mailCheck: MailCheck,
  menu: Menu,
  message: MessageSquare,
  minus: Minus,
  more: MoreHorizontal,
  moreVertical: MoreVertical,
  package: Package,
  packagePlus: PackagePlus,
  phone: Phone,
  plus: Plus,
  qr: QrCode,
  refresh: RefreshCw,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  shield: ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  stickyNote: StickyNote,
  trash: Trash2,
  unplug: Unplug,
  unlock: Unlock,
  user: User,
  wallet: Wallet,
  x: X,
};

export default function AppIcon({
  className,
  decorative,
  icon,
  label,
  name,
  size = "md",
  spin = false,
  strokeWidth = 1.8,
  ...props
}) {
  const Icon = icon || appIcons[name] || Info;
  const isDecorative = decorative ?? !label;

  return (
    <Icon
      aria-hidden={isDecorative ? "true" : undefined}
      aria-label={isDecorative ? undefined : label}
      className={clsx(styles.icon, styles[size] ?? styles.md, spin && styles.spin, className)}
      focusable="false"
      role={isDecorative ? undefined : "img"}
      strokeWidth={strokeWidth}
      {...props}
    />
  );
}
